{
 "title": "Health & performance summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(serverstatistics_server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current TPS",
   "type": "stat",
   "description": "Shows the server Ticks Per Second (TPS); which indicates how many ticks the server is able to process per second. Minecraft is capped at the maximum of 20. If you're dropping below this, it means your server is having trouble keeping up.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ticks_per_second{serverstatistics_server=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Current average MSPT",
   "type": "stat",
   "description": "Shows the Milliseconds Per Tick (MSPT); which indicates how many milliseconds the server spent processing each tick. Anything below 50ms is 20 TPS, anything higher means you're losing TPS. The further you stay away from 50ms, the further you are from losing that 20 TPS. Available on Paper servers only.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "milliseconds_per_tick_average{serverstatistics_server=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "description": "A simple calculation of how much memory is used compared to how much is available in total. Because of Java's lazy memory usage and garbage collection (GC), it's natural for this to actively go up and down.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(runtime_used_memory{serverstatistics_server=~\"$server\"} / runtime_total_memory{serverstatistics_server=~\"$server\"}) * 100"
    }
   ]
  },
  {
   "title": "Used storage",
   "type": "stat",
   "description": "Shows the percentage of storage capacity used by the server. Capacity is looked at from the execution directory of the Java process.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((disk_free_value{serverstatistics_server=~\"$server\"} / disk_total_value{serverstatistics_server=~\"$server\"}) * 100)"
    }
   ]
  },
  { "title": "System health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Ticks Per Second",
   "type": "graph",
   "description": "Shows the server Ticks Per Second (TPS); which indicates how many ticks the server is able to process per second. Minecraft is capped at the maximum of 20. If you're dropping below this, it means your server is having trouble keeping up.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ticks_per_second{serverstatistics_server=~\"$server\"}",
     "legendFormat": "1-minute average"
    }
   ]
  },
  {
   "title": "Milliseconds Per Tick",
   "type": "graph",
   "description": "Shows the Milliseconds Per Tick (MSPT); which indicates how many milliseconds the server spent processing each tick. Anything below 50ms is 20 TPS, anything higher means you're losing TPS. The further you stay away from 50ms, the further you are from losing that 20 TPS. Available on Paper servers only.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "milliseconds_per_tick_minimum{serverstatistics_server=~\"$server\"}",
     "legendFormat": "Minimum"
    },
    {
     "expr": "milliseconds_per_tick_average{serverstatistics_server=~\"$server\"}",
     "legendFormat": "Average"
    },
    {
     "expr": "milliseconds_per_tick_maximum{serverstatistics_server=~\"$server\"}",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "Ticks Per Second",
   "type": "graph",
   "description": "A simple calculation of how much memory is used compared to how much is available in total. Because of Java's lazy memory usage and garbage collection (GC), it's natural for this to actively go up and down.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(runtime_used_memory{serverstatistics_server=~\"$server\"} / runtime_total_memory{serverstatistics_server=~\"$server\"}) * 100",
     "legendFormat": "1-minute average"
    }
   ]
  },
  {
   "title": "Available storage",
   "type": "graph",
   "description": "Shows the server Ticks Per Second (TPS); which indicates how many ticks the server is able to process per second. Minecraft is capped at the maximum of 20. If you're dropping below this, it means your server is having trouble keeping up.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_total_value{serverstatistics_server=~\"$server\"}",
     "legendFormat": "Total capacity"
    },
    {
     "expr": "disk_total_value{serverstatistics_server=~\"$server\"} - disk_free_value{serverstatistics_server=~\"$server\"}",
     "legendFormat": "Used storage"
    }
   ]
  }
 ]
}