{
 "title": "Player overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(serverstatistics_server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Online players (selected server)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "players" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(online_players{serverstatistics_server=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Online players (all servers)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "players" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(online_players)" }
   ]
  },
  {
   "title": "Entities by world",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "players" } },
   "yaxes": [
    { "format": "players" }
   ],
   "targets": [
    {
     "expr": "sum(online_players{serverstatistics_server=~\"$server\"}) by (world)",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Online players by server",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "players" } },
   "yaxes": [
    { "format": "players" }
   ],
   "targets": [
    {
     "expr": "sum(online_players) by (serverstatistics_server)",
     "legendFormat": "{{serverstatistics_server}}"
    }
   ]
  }
 ]
}