{
 "title": "Entity overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(serverstatistics_server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total entities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "entities" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_entities{serverstatistics_server=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Total entities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "entities" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_tile_entities{serverstatistics_server=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Entities by type",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "entities" } },
   "yaxes": [
    { "format": "entities" }
   ],
   "targets": [
    {
     "expr": "sum(total_entities{serverstatistics_server=~\"$server\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Tile entities by type",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "tile entities" } },
   "yaxes": [
    { "format": "tile entities" }
   ],
   "targets": [
    {
     "expr": "sum(total_tile_entities{serverstatistics_server=~\"$server\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Entities by world",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "entities" } },
   "yaxes": [
    { "format": "entities" }
   ],
   "targets": [
    {
     "expr": "sum(total_entities{serverstatistics_server=~\"$server\"}) by (world)",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Tile entities by world",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "tile entities" } },
   "yaxes": [
    { "format": "tile entities" }
   ],
   "targets": [
    {
     "expr": "sum(total_tile_entities{serverstatistics_server=~\"$server\"}) by (world)",
     "legendFormat": "{{world}}"
    }
   ]
  }
 ]
}